# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myTestApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myTestApp
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  

  platform :ios, '9.0'
  target 'myTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'myTestApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myTestApp-tvOS

  target 'myTestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
